services:
  frontend:
    image: ${DOCKER_USER}/nuxt-prod:latest
    environment:
      NUXT_API_SECURE: "true"
      NUXT_API_DOMAIN: "api.deep-cosmo.ru"
      NUXT_API_PREFIX: "api/v1"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped  # Авторестарт при падении
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]  # Проверяем доступность
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
