name: Deploy Nuxt 3 SSR

on:
  push:
    branches: [master]  # Триггер на пуш в master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # --- Шаг 1: Забираем код ---
      - uses: actions/checkout@v4

      # --- Шаг 2: Логинимся в Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Шаг 3: Собираем образ и пушим ---
      - name: Build and Push Docker Image
        run: ls -la

      # --- Шаг 4: Деплой на сервер через SSH ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Останавливаем старый контейнер
            docker compose -f ~/nuxt-app/docker-compose.yml down || true

            # Забираем новый образ
            docker pull ${{ secrets.DOCKER_USER }}/nuxt-prod:latest

            # Запускаем
            docker compose -f ~/nuxt-app/docker-compose.yml up -d

            # Чистим старые образы (опционально)
            docker image prune -f
