name: Deploy Nuxt 3 SSR

on:
  push:
    branches: [master]  # Триггер на пуш в master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # --- Шаг 1: Забираем код ---
      - uses: actions/checkout@v4

      # --- Шаг 2: Логинимся в Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Шаг 3: Собираем образ и пушим ---
      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USER }}/nuxt-prod:latest .
          docker push ${{ secrets.DOCKER_USER }}/nuxt-prod:latest

      # --- Шаг 4: Деплой на сервер через SSH ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/ar69tem/data/www/deep-cosmo.ru/nuxt3-project-np
            docker compose down || true
            # docker compose pull
            docker rmi ${{ secrets.DOCKER_USER }}/nuxt-prod:latest  # Удаляем старый образ
            docker compose up -d --build
            docker image prune -f  # Очистка старых образов
