name: Deploy Nuxt 3 SSR

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build --no-cache \
            --build-arg NUXT_PUBLIC_API_DOMAIN=${{ secrets.NUXT_PUBLIC_API_DOMAIN }} \
            --build-arg NUXT_PUBLIC_API_PREFIX=${{ secrets.NUXT_PUBLIC_API_PREFIX }} \
            --build-arg NUXT_PUBLIC_API_SECURE=${{ secrets.NUXT_PUBLIC_API_SECURE }} \
            --build-arg NUXT_PUBLIC_SITE_URL=${{ secrets.NUXT_PUBLIC_SITE_URL }} \
            --build-arg NUXT_PUBLIC_SITE_NAME=${{ secrets.NUXT_PUBLIC_SITE_NAME }} \
            --build-arg NUXT_PUBLIC_SITE_DESCRIPTION=${{ secrets.NUXT_PUBLIC_SITE_DESCRIPTION }} \
            --build-arg NUXT_PUBLIC_SITE_INDEXABLE=${{ secrets.NUXT_PUBLIC_SITE_INDEXABLE }} \
            -t ${{ secrets.DOCKER_USER }}/nuxt-prod:latest .
          docker push ${{ secrets.DOCKER_USER }}/nuxt-prod:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходим в директорию проекта
            cd /var/www/ar69tem/data/www/deep-cosmo.ru/opt/nuxt-app

            # 1. Генерируем .env файл из GitHub Secrets
            cat << 'EOF' > .env
            DOCKER_USER=${{ secrets.DOCKER_USER }}
            NUXT_PUBLIC_API_DOMAIN=${{ secrets.NUXT_PUBLIC_API_DOMAIN }}
            NUXT_PUBLIC_API_PREFIX=${{ secrets.NUXT_PUBLIC_API_PREFIX }}
            NUXT_PUBLIC_API_SECURE=${{ secrets.NUXT_PUBLIC_API_SECURE }}
            NUXT_PUBLIC_SITE_URL=${{ secrets.NUXT_PUBLIC_SITE_URL }}
            NUXT_PUBLIC_SITE_NAME=${{ secrets.NUXT_PUBLIC_SITE_NAME }}
            NUXT_PUBLIC_SITE_DESCRIPTION=${{ secrets.NUXT_PUBLIC_SITE_DESCRIPTION }}
            NUXT_PUBLIC_SITE_INDEXABLE=${{ secrets.NUXT_PUBLIC_SITE_INDEXABLE }}
            EOF

            # 2. Защищаем файл (только для владельца)
            chmod 600 .env

            # 3. Перезапускаем контейнеры
            docker compose down --rmi all
            docker compose pull
            docker compose up -d
            docker image prune -f
